// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NisanDavetiye.DAL.Data;

#nullable disable

namespace NisanDavetiye.DAL.Migrations
{
    [DbContext(typeof(NisanDavetiyeDbContext))]
    [Migration("20260718131500_UpdateEtkinlikSaati1930")]
    partial class UpdateEtkinlikSaati1930
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("NisanDavetiye.DAL.Entities.DavetiyeAyarlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcilisVideoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BasHarpler")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CiftFotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DamatAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DavetUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EtkinlikTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("GaleriDriveKlasorUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GaleriYuklemeAcik")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GelinAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaritaEmbedUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaritaLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HosgeldinMetni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KapakGorselUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MekanAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MuzikUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PanelUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZarfArkaPlanUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavetiyeAyarlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcilisVideoUrl = "/assets/video/intro.mp4",
                            Adres = "Cumhuriyet Mah. Malatya Cad. Hazar Dağlı Kavşağı, Merkez / Elazığ",
                            BasHarpler = "C & E",
                            Baslik = "Nişanımıza Davetlisiniz",
                            CiftFotoUrl = "/assets/images/cift.jpg",
                            DamatAdi = "Emre",
                            DavetUid = "24temmuz2026",
                            EtkinlikTarihi = new DateTime(2026, 7, 24, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            GaleriDriveKlasorUrl = "",
                            GaleriYuklemeAcik = false,
                            GelinAdi = "Ceren",
                            HaritaEmbedUrl = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3062.886!2d39.1768327!3d38.666045!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4076c1bca9e9b6c1%3A0xf6d1059611873dee!2sWinner%27s%20Davet%20Evi!5e0!3m2!1str!2str!4v1",
                            HaritaLink = "https://maps.app.goo.gl/6peSAmVGAKMruPxo6",
                            HosgeldinMetni = "Bu mutlu günümüzde sizleri de aramızda görmekten büyük mutluluk duyarız. Sevgi ve saygılarımızla.",
                            KapakGorselUrl = "/assets/video/hero.mp4",
                            MekanAdi = "Winner's Davet Evi",
                            MuzikUrl = "/assets/audio/ballerina.mp3",
                            PanelUid = "",
                            ZarfArkaPlanUrl = ""
                        });
                });

            modelBuilder.Entity("NisanDavetiye.DAL.Entities.GaleriResmi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltMetin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Onaylandi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GaleriResimleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltMetin = "Anı 1",
                            DriveFileId = "",
                            Onaylandi = true,
                            Sira = 1,
                            Url = "/assets/images/galeri-1.jpg",
                            YuklemeTarihi = new DateTime(2026, 7, 18, 12, 53, 52, 104, DateTimeKind.Utc).AddTicks(2446)
                        },
                        new
                        {
                            Id = 2,
                            AltMetin = "Anı 2",
                            DriveFileId = "",
                            Onaylandi = true,
                            Sira = 2,
                            Url = "/assets/images/galeri-2.jpg",
                            YuklemeTarihi = new DateTime(2026, 7, 18, 12, 53, 52, 104, DateTimeKind.Utc).AddTicks(3204)
                        },
                        new
                        {
                            Id = 3,
                            AltMetin = "Anı 3",
                            DriveFileId = "",
                            Onaylandi = true,
                            Sira = 3,
                            Url = "/assets/images/galeri-3.jpg",
                            YuklemeTarihi = new DateTime(2026, 7, 18, 12, 53, 52, 104, DateTimeKind.Utc).AddTicks(3206)
                        },
                        new
                        {
                            Id = 4,
                            AltMetin = "Anı 4",
                            DriveFileId = "",
                            Onaylandi = true,
                            Sira = 4,
                            Url = "/assets/images/galeri-4.jpg",
                            YuklemeTarihi = new DateTime(2026, 7, 18, 12, 53, 52, 104, DateTimeKind.Utc).AddTicks(3207)
                        });
                });

            modelBuilder.Entity("NisanDavetiye.DAL.Entities.RsvpKayit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AdminListedenGizli")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Katilacak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RsvpKayitlari");
                });

            modelBuilder.Entity("NisanDavetiye.DAL.Entities.TimelineOgesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Saat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TimelineOgeleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Ailelerimizin geleneksel isteme merasimi.",
                            Baslik = "İsteme Merasimi",
                            Saat = "19:00",
                            Sira = 1
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Nişan merasimimiz başlıyor.",
                            Baslik = "Nişan Töreni",
                            Saat = "19:30",
                            Sira = 2
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Yemek ikramımız başlayacaktır.",
                            Baslik = "Akşam Yemeği",
                            Saat = "20:00",
                            Sira = 3
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Gecemiz müzik ve eğlence eşliğinde devam edecektir.",
                            Baslik = "Müzik & Eğlence",
                            Saat = "20:30",
                            Sira = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
