// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NisanDavetiye.DAL.Data;

#nullable disable

namespace NisanDavetiye.DAL.Migrations
{
    [DbContext(typeof(NisanDavetiyeDbContext))]
    [Migration("20260701101518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("NisanDavetiye.DAL.Entities.DavetiyeAyarlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcilisVideoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BasHarpler")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CiftFotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DamatAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EtkinlikTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("GelinAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaritaEmbedUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaritaLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HosgeldinMetni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KapakGorselUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MekanAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MuzikUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZarfArkaPlanUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavetiyeAyarlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcilisVideoUrl = "/assets/video/acilis.mp4",
                            Adres = "Bebek, Cevdet Paşa Cd. No:12, Beşiktaş/İstanbul",
                            BasHarpler = "E & C",
                            Baslik = "Nişanımıza Davetlisiniz",
                            CiftFotoUrl = "/assets/images/cift.jpg",
                            DamatAdi = "Emre",
                            EtkinlikTarihi = new DateTime(2026, 8, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            GelinAdi = "Ceren",
                            HaritaEmbedUrl = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3006.0!2d29.043!3d41.077!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDHCsDA0JzM3LjIiTiAyOcKwMDInMzQuOCJF!5e0!3m2!1str!2str!4v1",
                            HaritaLink = "https://maps.google.com/?q=Bebek+İstanbul",
                            HosgeldinMetni = "Bu mutlu günümüzde sizleri de aramızda görmekten büyük mutluluk duyarız. Sevgi ve saygılarımızla.",
                            KapakGorselUrl = "/assets/images/kapak.jpg",
                            MekanAdi = "Grand Bosphorus Salon",
                            MuzikUrl = "/assets/audio/muzik.mp3",
                            ZarfArkaPlanUrl = "/assets/images/zarf-arka.jpg"
                        });
                });

            modelBuilder.Entity("NisanDavetiye.DAL.Entities.GaleriResmi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltMetin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GaleriResimleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltMetin = "Anı 1",
                            Sira = 1,
                            Url = "/assets/images/galeri-1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AltMetin = "Anı 2",
                            Sira = 2,
                            Url = "/assets/images/galeri-2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AltMetin = "Anı 3",
                            Sira = 3,
                            Url = "/assets/images/galeri-3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            AltMetin = "Anı 4",
                            Sira = 4,
                            Url = "/assets/images/galeri-4.jpg"
                        });
                });

            modelBuilder.Entity("NisanDavetiye.DAL.Entities.RsvpKayit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Katilacak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RsvpKayitlari");
                });

            modelBuilder.Entity("NisanDavetiye.DAL.Entities.TimelineOgesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Saat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TimelineOgeleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Misafirlerimizi karşılıyoruz.",
                            Baslik = "Karşılama",
                            Saat = "18:30",
                            Sira = 1
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Nişan merasimimiz başlıyor.",
                            Baslik = "Nişan Töreni",
                            Saat = "19:00",
                            Sira = 2
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Kokteyl ve fotoğraf çekimi.",
                            Baslik = "Kokteyl",
                            Saat = "20:00",
                            Sira = 3
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Akşam yemeği servisi.",
                            Baslik = "Akşam Yemeği",
                            Saat = "21:00",
                            Sira = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
